version: "3"

services:
  server:
    build: ./
    ports:
      - "7777:7777"
      - "7778:7778"
      - "7779:7779"
    depends_on:
      - redis
      - mongo
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"